name: MSYS2 Info

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: .gitconfig
      run:  git config -l
    - name: checkout
      uses: actions/checkout@v2

    - name: Show ENV
      run:  gci env:* | sort-object name

    - name: Show PATH
      run:  Write-Host $env:PATH.replace(";", "`n")

    - name: Where is?
      run:  |
        # where queries
        $dash = "—" * 60
        $dashs = "—" * 20
        write-host "$dash openssl"              ; where.exe openssl.exe
        write-host "$dash libcrypto-1_1-x64.dll"; where.exe libcrypto-1_1-x64.dll
        write-host "$dash libssl-1_1-x64.dll"   ; where.exe libssl-1_1-x64.dll
        write-host "`n$dash bash"               ; where.exe bash.exe
        write-host "`n$dash make"               ; where.exe make.exe
        write-host "`n$dash gcc"                ; where.exe gcc.exe
        write-host "`n$dash 7z.exe"             ; where.exe 7z.exe

    - name: load ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x

    - name: Windows MSYS2
      uses: MSP-Greg/msys2-action@master
      with:
        base: update
        mingw: openssl
        msys2: automake1.16 bison curl patch sed

    - name: List MinGW packages
      run:  pacman -Q

    - name: Where is? and gcc
      run:  |
        # where queries and gcc
        $dash = "—" * 60
        $dashs = "—" * 20
        write-host "$dash openssl"              ; where.exe openssl.exe
        write-host "$dash libcrypto-1_1-x64.dll"; where.exe libcrypto-1_1-x64.dll
        write-host "$dash libssl-1_1-x64.dll"   ; where.exe libssl-1_1-x64.dll
        write-host "`n$dash bash"               ; where.exe bash.exe
        write-host "`n$dash make"               ; where.exe make.exe
        write-host "`n$dash gcc"                ; where.exe gcc.exe
        write-host "`n$dash 7z.exe"             ; where.exe 7z.exe
        Write-host "`n$dashs C:\ProgramData\Chocolatey\bin\gcc --version"
        C:\ProgramData\Chocolatey\bin\gcc --version
        Write-Host "`n$dashs C:\Strawberry\c\bin\gcc --version"
        C:\Strawberry\c\bin\gcc --version
        Write-Host "`n$dashs gcc --version"
        gcc --version
