name: MSYS2 Install

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Show ENV
      run:  gci env:* | sort-object name
    - name: load ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Windows MSYS2
      uses: MSP-Greg/msys2-action@master
      with:
        base: update
        mingw: openssl
        msys2: automake1.16 bison curl patch sed
    - name: List MinGW packages
      run:  pacman -Q
    - name: Where is?
      run:  |
        where.exe openssl.exe
        where.exe make.exe
        where.exe gcc.exe
        where.exe 7z.exe
