name: MSYS2 Install

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: set
      run:  set
    - name: load ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Add MSYS2 paths
      uses: MSP-Greg/msys2-action/add_paths@master
    - name: Update MSYS2
      uses: MSP-Greg/msys2-action/update_msys2@master
    - name: Update OpenSSL
      uses: MSP-Greg/msys2-action/update_openssl@master
    - name: Where is?
      run:  |
        where.exe openssl.exe
        where.exe make.exe
        where.exe gcc.exe
        where.exe cmake.exe
